### ISSUE TITLE
EBMV and LINTRANS columns

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#57] opened 2017-08-09 00:54 UTC
Originally from desihub/surveysim#45 but bringing it over here since it applies to files written by desisurvey:

> In desisim.quickcat we use 'EBMV' (E(B-V)) and LINTRANS to estimate the redshift efficiency. Would it be possible to have those two columns in the progress_* files?

**Comment by dkirkby** [comment] 2017-08-09 16:45
Closed as a duplicate of #54

**Closed by dkirkby** 2017-08-09 16:45 UTC
Labels: duplicate
